const express=require("express");
const cors=require("cors");
const jwt=require("jsonwebtoken");
const bcrypt=require("bcryptjs");
const {Pool}=require("pg");
const path=require("path");
const app=express(), PORT=process.env.PORT||3000;
const SECRET=process.env.JWT_SECRET||"CHANGE_ME";
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
app.use(cors());app.use(express.json({limit:"2mb"}));app.use(express.static(path.join(__dirname,"public")));
const wc=t=>String(t||"").trim()?String(t).trim().split(/\s+/).filter(Boolean).length:0;
const defaults=[
["English","Easy","General","Daily Practice","Typing is a useful skill that improves with regular practice. Focus on accuracy first and speed will follow naturally. Regular practice helps you become comfortable with the keyboard and reduces common mistakes. A calm pace, correct finger placement, and attention to every word can make your typing more reliable. As your accuracy improves, your speed will increase naturally. Try to practice for a few minutes every day and compare your results over time. Consistency is more important than rushing through a single test."],
["English","Medium","Education","Learning Skills","Consistent practice, correct finger placement, and careful attention to mistakes can make typing faster and more accurate. Good typing skills are useful for students, office workers, teachers, and anyone who spends time on a computer. When you practice, try to keep your eyes on the passage instead of looking down at the keyboard. Correct mistakes carefully and learn which keys cause the most errors. A daily routine can improve both speed and confidence. Over time, even a short practice session can produce measurable progress. The goal is not only to type quickly, but also to type accurately and comfortably."],
["English","Hard","Technology","Digital World","Modern workplaces depend on efficient digital communication, and strong keyboard skills can save valuable time every day. People write reports, prepare documents, answer messages, enter information, and work with online applications for many hours. Fast and accurate typing makes these tasks easier while reducing unnecessary corrections. Technology continues to change the way people study and work, but the ability to communicate clearly remains important. Building a reliable typing habit takes patience, repetition, and concentration. A structured practice routine can help a learner measure improvement and prepare for formal typing examinations."],
["Hindi","Easy","General","दैनिक अभ्यास","नियमित अभ्यास से टाइपिंग की गति और शुद्धता दोनों बेहतर होती हैं। पहले सही टाइपिंग पर ध्यान दें और धीरे धीरे गति बढ़ाएं। रोज कुछ समय अभ्यास करने से कीबोर्ड पर उंगलियों की स्थिति समझ में आती है और सामान्य गलतियां कम होती हैं। जल्दी टाइप करने की कोशिश करने के बजाय प्रत्येक शब्द को ध्यान से लिखना अधिक उपयोगी है। जब शुद्धता अच्छी हो जाती है तब गति अपने आप बढ़ने लगती है। लगातार अभ्यास करने वाला विद्यार्थी कुछ ही समय में अपने परिणामों में सुधार देख सकता है। इसलिए हर दिन थोड़ी देर शांत मन से अभ्यास करें और अपनी प्रगति को रिकॉर्ड करते रहें।"],
["Hindi","Medium","Education","शिक्षा और अभ्यास","लगातार अभ्यास, सही उंगलियों की स्थिति और गलतियों पर ध्यान देने से हिंदी टाइपिंग में अच्छा सुधार किया जा सकता है। विद्यार्थी को प्रतिदिन एक निश्चित समय टाइपिंग के लिए रखना चाहिए। अभ्यास के दौरान शब्दों को ध्यान से पढ़ना और फिर उन्हें सही क्रम में लिखना जरूरी है। यदि किसी अक्षर या शब्द में बार बार गलती हो रही है तो उस हिस्से का अलग से अभ्यास करना चाहिए। केवल गति बढ़ाने पर ध्यान देने से शुद्धता कम हो सकती है, इसलिए दोनों का संतुलन बनाए रखना जरूरी है। नियमित अभ्यास से आत्मविश्वास बढ़ता है और परीक्षा के समय समय प्रबंधन भी बेहतर होता है।"],
["Hindi","Hard","Technology","तकनीकी दुनिया","आज के डिजिटल युग में तेज और सटीक टाइपिंग पढ़ाई, नौकरी और ऑनलाइन कार्यों के लिए एक महत्वपूर्ण कौशल बन चुकी है। कंप्यूटर पर दस्तावेज तैयार करने, जानकारी दर्ज करने, संदेश लिखने और विभिन्न ऑनलाइन सेवाओं का उपयोग करने में टाइपिंग की भूमिका बहुत महत्वपूर्ण है। अच्छी गति के साथ शुद्धता बनाए रखना किसी भी टाइपिंग परीक्षा की तैयारी में उपयोगी होता है। अभ्यास करते समय उम्मीदवार को अपनी गलतियों का विश्लेषण करना चाहिए और कठिन शब्दों पर विशेष ध्यान देना चाहिए। नियमित अभ्यास, सही मुद्रा और कीबोर्ड पर उंगलियों की उचित स्थिति से प्रदर्शन में लगातार सुधार किया जा सकता है।"]
];
async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS passages(id SERIAL PRIMARY KEY,language TEXT NOT NULL,difficulty TEXT NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,text TEXT NOT NULL,min_words INT NOT NULL DEFAULT 0,word_count INT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS exams(id SERIAL PRIMARY KEY,name TEXT NOT NULL,code TEXT UNIQUE NOT NULL,organization TEXT DEFAULT 'SR Typing',language TEXT NOT NULL,duration INT DEFAULT 300,required_wpm INT DEFAULT 30,required_accuracy NUMERIC DEFAULT 90,description TEXT DEFAULT '',active BOOLEAN DEFAULT TRUE);
 CREATE TABLE IF NOT EXISTS results(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,test_type TEXT,language TEXT,duration INT,wpm NUMERIC,accuracy NUMERIC,errors INT,gross_wpm NUMERIC,net_wpm NUMERIC,cpm NUMERIC,backspaces INT,focus_losses INT,category TEXT,difficulty TEXT,passage_title TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS exam_attempts(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,exam_id INT REFERENCES exams(id),candidate_name TEXT,roll_no TEXT,language TEXT,duration INT,wpm NUMERIC,accuracy NUMERIC,errors INT,gross_wpm NUMERIC,net_wpm NUMERIC,cpm NUMERIC,backspaces INT,focus_losses INT,passed BOOLEAN,status TEXT DEFAULT 'submitted',passage_title TEXT,started_at TIMESTAMPTZ,submitted_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS site_content(content_key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TIMESTAMPTZ DEFAULT NOW());`);
 if(!(await pool.query("SELECT 1 FROM users WHERE email=$1",["admin@srtyping.local"])).rowCount){let h=await bcrypt.hash(process.env.ADMIN_PASSWORD||"Admin@12345",10);await pool.query("INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,'admin')",["Administrator","admin@srtyping.local",h])}
 if((await pool.query("SELECT COUNT(*) n FROM passages")).rows[0].n==="0"){for(let p of defaults){let min=p[0]==="English"?150:125;await pool.query("INSERT INTO passages(language,difficulty,category,title,text,min_words,word_count) VALUES($1,$2,$3,$4,$5,$6,$7)",[...p,min,wc(p[4])])}}
 if((await pool.query("SELECT COUNT(*) n FROM exams")).rows[0].n==="0"){await pool.query("INSERT INTO exams(name,code,language,duration,required_wpm,required_accuracy,description) VALUES($1,$2,$3,300,30,90,$4)",["SR Typing English Exam","ENG","English","5 minute English typing examination"]);await pool.query("INSERT INTO exams(name,code,language,duration,required_wpm,required_accuracy,description) VALUES($1,$2,$3,300,25,90,$4)",["SR Typing Hindi Exam","HIN","Hindi","5 minute Hindi typing examination"])}
 for(const [k,v] of Object.entries({hero_title:"Master Your Typing Skills",hero_subtitle:"A complete Hindi & English typing platform for practice, speed tests and government exam preparation.",announcement:"SR Typing is now live — practice daily and improve your speed.",contact_email:"support@srtyping.local",about:"SR Typing is an all-in-one typing practice and exam preparation platform."}))await pool.query("INSERT INTO site_content(content_key,value) VALUES($1,$2) ON CONFLICT DO NOTHING",[k,v]);
}
function auth(req,res,next){try{let h=req.headers.authorization||"";req.user=jwt.verify(h.replace("Bearer ",""),SECRET);next()}catch(e){res.status(401).json({error:"Login required"})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({error:"Admin access required"});next()}
const su=u=>({id:u.id,name:u.name,email:u.email,role:u.role,created_at:u.created_at});
app.get("/api/health",async(q,s)=>{try{await pool.query("SELECT 1");s.json({ok:true,version:"10.0-online-postgresql"})}catch(e){s.status(500).json({ok:false,error:e.message})}});
app.get("/api/site-content",async(q,s)=>{let r=await pool.query("SELECT * FROM site_content");s.json({content:Object.fromEntries(r.rows.map(x=>[x.content_key,x.value]))})});
app.post("/api/register",async(q,s)=>{try{let b=q.body||{},e=String(b.email||"").toLowerCase().trim();if(!b.name||!e||String(b.password||"").length<6)return s.status(400).json({error:"Invalid registration"});if((await pool.query("SELECT 1 FROM users WHERE email=$1",[e])).rowCount)return s.status(409).json({error:"Email already registered"});let h=await bcrypt.hash(b.password,10),r=await pool.query("INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING *",[b.name,e,h]),u=r.rows[0];s.json({token:jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:"7d"}),user:su(u)})}catch(e){s.status(500).json({error:e.message})}});
app.post("/api/login",async(q,s)=>{let r=await pool.query("SELECT * FROM users WHERE email=$1",[String(q.body.email||"").toLowerCase().trim()]);if(!r.rowCount||!(await bcrypt.compare(String(q.body.password||""),r.rows[0].password_hash)))return s.status(401).json({error:"Invalid email or password"});let u=r.rows[0];s.json({token:jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:"7d"}),user:su(u)})});
app.get("/api/me",auth,async(q,s)=>{let r=await pool.query("SELECT * FROM users WHERE id=$1",[q.user.id]);s.json({user:su(r.rows[0])})});
app.get("/api/passages",async(q,s)=>{let r=await pool.query("SELECT * FROM passages WHERE ($1='' OR language=$1) AND ($2='' OR difficulty=$2) AND ($3='' OR $3='All' OR category=$3) ORDER BY RANDOM()",[q.query.language||"",q.query.difficulty||"",q.query.category||""]);s.json({passages:r.rows})});
app.get("/api/exams",async(q,s)=>s.json({exams:(await pool.query("SELECT * FROM exams WHERE active=true ORDER BY id")).rows}));
app.get("/api/exams/:id/full",async(q,s)=>{let e=(await pool.query("SELECT * FROM exams WHERE id=$1 AND active=true",[q.params.id])).rows[0];if(!e)return s.status(404).json({error:"Exam not found"});let min=e.language==="English"?150:125,p=(await pool.query("SELECT * FROM passages WHERE language=$1 AND word_count >= $2 ORDER BY RANDOM() LIMIT 1",[e.language,min])).rows[0];if(!p)return s.status(404).json({error:"No qualifying passage available"});s.json({exam:e,passage:p})});
app.post("/api/results",auth,async(q,s)=>{let b=q.body||{},r=await pool.query("INSERT INTO results(user_id,test_type,language,duration,wpm,accuracy,errors,gross_wpm,net_wpm,cpm,backspaces,focus_losses,category,difficulty,passage_title) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *",[q.user.id,b.test_type||"practice",b.language||"",b.duration||0,b.wpm||0,b.accuracy||0,b.errors||0,b.gross_wpm||0,b.net_wpm||b.wpm||0,b.cpm||0,b.backspaces||0,b.focus_losses||0,b.category||"",b.difficulty||"",b.passage_title||""]);s.json({success:true,result:r.rows[0]})});
app.get("/api/results/me",auth,async(q,s)=>s.json({results:(await pool.query("SELECT * FROM results WHERE user_id=$1 ORDER BY id DESC LIMIT 100",[q.user.id])).rows}));
app.get("/api/dashboard",auth,async(q,s)=>{let a=(await pool.query("SELECT * FROM results WHERE user_id=$1 ORDER BY id DESC",[q.user.id])).rows,avg=k=>a.length?a.reduce((z,x)=>z+Number(x[k]||0),0)/a.length:0;s.json({stats:{totalTests:a.length,bestWpm:a.length?Math.max(...a.map(x=>Number(x.net_wpm||0))):0,avgWpm:avg("net_wpm"),avgAccuracy:avg("accuracy")},recent:a.slice(0,10)})});
app.post("/api/exams/:id/submit",auth,async(q,s)=>{let e=(await pool.query("SELECT * FROM exams WHERE id=$1",[q.params.id])).rows[0],b=q.body||{};if(!e)return s.status(404).json({error:"Exam not found"});let duration=Number(b.duration)||300,chars=Number(b.chars)||0,errors=Number(b.errors)||0,mins=duration/60,gross=chars/5/mins,net=Math.max(0,gross-errors/mins),acc=chars?Math.max(0,(chars-errors)/chars*100):100,pass=net>=e.required_wpm&&acc>=e.required_accuracy,r=await pool.query("INSERT INTO exam_attempts(user_id,exam_id,candidate_name,roll_no,language,duration,wpm,accuracy,errors,gross_wpm,net_wpm,cpm,backspaces,focus_losses,passed,passage_title,started_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,NOW()) RETURNING id",[q.user.id,e.id,b.candidateName,b.rollNo,e.language,duration,net,acc,errors,gross,net,chars/mins,b.backspaces||0,b.focusLosses||0,pass,b.passageTitle||""]);let id=r.rows[0].id;s.json({success:true,attemptId:id,passed:pass,candidateName:b.candidateName,rollNo:b.rollNo,exam:e,score:{gross_wpm:gross,net_wpm:net,cpm:chars/mins,accuracy:acc},certificateNo:`SR-${e.code}-${String(id).padStart(6,"0")}`})});
app.get("/api/exam-attempts/me",auth,async(q,s)=>s.json({attempts:(await pool.query("SELECT a.*,e.name exam_name,e.organization FROM exam_attempts a JOIN exams e ON e.id=a.exam_id WHERE a.user_id=$1 ORDER BY a.id DESC LIMIT 100",[q.user.id])).rows}));
app.get("/api/exam-result/:id",auth,async(q,s)=>{let r=(await pool.query("SELECT a.*,e.name exam_name,e.code exam_code,e.organization,e.required_wpm,e.required_accuracy FROM exam_attempts a JOIN exams e ON e.id=a.exam_id WHERE a.id=$1 AND a.user_id=$2",[q.params.id,q.user.id])).rows[0];if(!r)return s.status(404).json({error:"Result not found"});s.json({result:r,certificateNo:`SR-${r.exam_code}-${String(r.id).padStart(6,"0")}`})});
app.get("/api/admin/users",auth,admin,async(q,s)=>s.json({users:(await pool.query("SELECT id,name,email,role,created_at FROM users ORDER BY id DESC")).rows}));
app.get("/api/admin/passages",auth,admin,async(q,s)=>s.json({passages:(await pool.query("SELECT * FROM passages ORDER BY id DESC")).rows}));
app.post("/api/admin/passages",auth,admin,async(q,s)=>{let b=q.body||{},n=wc(b.text),min=b.language==="English"?150:125;if(!b.language||!b.title||!b.text)return s.status(400).json({error:"Language, title and paragraph are required"});if(n<min)return s.status(400).json({error:`${b.language} passage needs at least ${min} words. Current: ${n}`});let r=await pool.query("INSERT INTO passages(language,difficulty,category,title,text,min_words,word_count) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[b.language,b.difficulty||"Medium",b.category||"General",b.title,b.text,min,n]);s.json({success:true,passage:r.rows[0]})});
app.delete("/api/admin/passages/:id",auth,admin,async(q,s)=>{await pool.query("DELETE FROM passages WHERE id=$1",[q.params.id]);s.json({success:true})});
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"public","index.html")));
init().then(()=>app.listen(PORT,()=>console.log(`SR Typing online-ready on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
